[project]
name = "umd-oaipmh-server"
version = "1.3.0-rc1"
dependencies = [
    "flask",
    "lxml",
    "oai-repo",
    "pysolr",
    "python-dotenv",
    "PyYAML",
    "requests",
    "requests-jwtauth",
    "waitress",
    "Sickle"
]
[project.optional-dependencies]
test = [
    "pycodestyle",
    "pytest",
    "pytest-cov",
]
[project.scripts]
fcrepo-oaipmh-server = "oaipmh.server:run"
add-handles = "oaipmh.add_handles:main"
